<style type="text/css">

</style>
<div class="container-fluid">
  <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Categories</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800"><?= $categories_count['count'] == null ? "0" : $categories_count['count'] ?></div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-6 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Products</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800"><?= count($products) ?></div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar  fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            
          </div>
</div>





<?php if(isset($products)): ?>

<!-- Content Row -->    

<!-- Begin Page Content -->
<div class="container-fluid">

  <div class="card shadow mb-4">
    <div class="card-header">
      All Products
    </div>
   
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" width="100%" cellspacing="0" id="dataTable">
          <thead>
            <tr>
              <th>#</th>
              <th>Product</th>
              <th>Category</th>
              <th>Description</th>
              <th>Price</th>
            </tr>
          </thead>
         
          <tbody>

              <?php $counter = 0;  foreach ($products as $item ) { $counter = $counter+1; ?>
                <tr>
                  <td> <?= $counter ?> </td>
                  <td> <?= $item['name'] ?> </td>
                  <td> <?= $item['category_name'] ?> </td>
                  <td> <?= substr($item['description'], 0, 500); ?> </td>
                  <td> <?= $item['price'] ?> </td>
                </tr>
              <?php } ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>