<header>
	<div class="container">
		<div class="row">
			<div class="col-md-3">
				<strong>LOGO</strong>
			</div>
			<div class="col-md-9">
				<ul class="nav justify-content-end custom-nav">
				  <li class="nav-item">
				    <a class="nav-link active" href="#">Home</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">About us</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Products</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Farm Education</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" href="#">Contact us</a>
				  </li>
				  
				</ul>
			</div>
		</div>
	</div>
</header>