<!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon ">
          <!-- <img src="/img/surebids_favicon.png" style="height: 42px"> -->
           <img class="img-profile rounded-circle" style="height: 42px; width: 42px; " src="/img/favicon.png">
        </div>
        <div class="sidebar-brand-text mx-3">FINETOUCH </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">
       <?php if(in_array("Dashboard", $user_permissions)): ?> 
      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="/dashboard">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>
      

      <!-- Divider -->
      <hr class="sidebar-divider">
      <?php endif; ?>

      <!-- Heading -->
      <div class="sidebar-heading d-none">
        MENU
      </div>
     
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEntries" aria-expanded="true" aria-controls="collapseEntries">
          <i class="fas fa-fw fa-cog"></i>
          <span>Categories/Products</span>
        </a>
        <div id="collapseEntries" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Categories:</h6>
            <a class="collapse-item" href="/categories">Manage Categories</a>
            <h6 class="collapse-header">Products:</h6>
            <a class="collapse-item" href="/products">Manage Products</a>
            <a class="collapse-item" href="/products/new">New Product</a>
          </div>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseEntries" aria-expanded="true" aria-controls="collapseEntries">
          <i class="fas fa-fw fa-cog"></i>
          <span>Site Data</span>
        </a>
        <div id="collapseEntries" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Manage site data:</h6>
            <a class="collapse-item" href="/sitedata/banners">Banners</a>
          </div>
        </div>
      </li>
      
    
      <?php 
      // if(in_array("Users", $user_permissions)): 
        ?> 
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUsers" aria-expanded="true" aria-controls="collapseUsers">
          <i class="fas fa-fw fa-cog"></i>
          <span>Users</span>
        </a>
        <div id="collapseUsers" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Manage Users:</h6>
            <a class="collapse-item" href="/users">Manage Users</a>
            <a class="collapse-item" href="/roles">Roles</a>
            <a class="collapse-item" href="/roles/permissions/view">Permissions</a>
          </div>
        </div>
      </li>
      <?php 
    // endif; 
    ?>

     

      
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->