  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row justify-content-center">
              
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <img class="mb-3" src="/bigwin_logo.png" style="height: 72px">
                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                    <p class="mb-4">We get it, stuff happens. Just enter your  phone number below and we'll send you a code to reset your password!</p>
                  </div>
                  <form class="user" method="POST" action="/auth/forgot">
                    <?php echo $this->flashSession->output(); ?>
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Phone..." name="phone">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block" disabled>
                      Reset Password
                    </button>
                  </form>
                  <hr>
                 
                  <div class="text-center">
                    <a class="small" href="/auth/login">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>