  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row justify-content-center">
              
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <!-- <img class="mb-3" src="/img/surebids_logo.png" style="height: 42px"> -->
                    <h1 class="h4 text-gray-900 mb-2">Reset Your Password</h1>
                    <p class="mb-4">Enter the details below to reset your password</p>
                  </div>
                  <form class="user" method="POST" action="/auth/reset">
                    <?php echo $this->flashSession->output(); ?>
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Phone..." name="phone" value="<?php if(isset($_GET['phone'])){ echo $_GET['phone']; } ?>">
                    </div>
                     <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Reset Code..." name="code">
                    </div>
                     <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter New Password..." name="password">
                    </div>
                     <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Confirm New Password..." name="password2">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </button>
                  </form>
                  <hr>
                 
                  <div class="text-center">
                    <a class="small" href="/auth/login">Already have an account? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>