        <!-- Begin Page Content -->
        <div class="container-fluid">

          <?php 


          ?>

          <!-- Page Heading -->
          <div class="mb-3" style="">
             <h1 class="h3 mb-1 text-gray-800">All Users</h1>
            
           <button data-toggle="modal" data-target="#userModalNew" class="btn btn-success btn-sm">Create User</button>
             
            
          </div>
         

          <!-- DataTales Example -->
          <div class="card shadow mb-4">
          
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Full Name</th>
                      <th>Phone</th>
                      <th>Role</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                    <?php foreach ($users as $item) {?>
                    <tr>
                      <td> <?= $item['full_name'] ?> </td>
                      <td> <?= $item['msisdn'] ?> </td>
                      <td> <?= $item['role_name'] ?> </td>
                     
                      <td> <button class="btn btn-sm btn-warning" data-toggle="modal" data-target="#userModal<?= $item['id'] ?>"> <i class="fa fa-edit"></i> EDIT</button> </td>
                    </tr>
                    <?php  } ?>
                   
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>

<!-- Modal -->
<?php foreach ($users as $user) {?>
<div class="modal fade" id="userModal<?= $user['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Edit User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="/users/edit/<?= $user['id'] ?>" method="POST">
        <div class="form-group ">
          <label for="inputEmail4">Role</label>
         <select id="inputState" class="form-control" name="role" >
            <option value="<?= $user['role_id'] ?>" selected><?= $user['role_name'] ?></option>
            <?php foreach ($roles as $role) { ?>
               <option value="<?= $role['id'] ?>"> <?= $role['name'] ?> </option>
            <?php } ?>
            
          </select>
        </div>
                 
           <div class="form-group ">
            <label for="fname">Full Name</label>
            <input type="text" class="form-control" placeholder="Full Name" name="full_name" value="<?= $user['full_name'] ?>" required>
          </div>
          <div class="form-group ">
            <label for="lname">Phone *</label>
            <input type="text" class="form-control" placeholder="Phone" name="phone" value="<?= $user['msisdn'] ?>" required readonly>
          </div>
          <div class="form-group ">
            <label for="lname">Password</label>
            <input type="password" class="form-control" placeholder="Password" name="password" value="" >
          </div>
          
        <button type="submit" class="btn btn-primary form-control">Update User</button>
      </form>
      </div>
      
    </div>
  </div>
</div>
<?php  } ?>



<div class="modal fade" id="userModalNew" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Create User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form action="/users/new" method="POST">
                  <div class="form-group ">
                    <label for="inputEmail4">Role</label>
                   <select id="inputState" class="form-control" name="role" >
                      <?php foreach ($roles as $role) { ?>
                         <option value="<?= $role['id'] ?>"> <?= $role['name'] ?> </option>
                      <?php } ?>
                      
                    </select>
                  </div>
                   <div class="form-group ">
                    <label for="fname">Full Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="full_name" required>
                  </div>
                  <div class="form-group ">
                    <label for="lname">Phone</label>
                    <input type="text" class="form-control" placeholder="Phone" name="phone" required>
                  </div>
                  <div class="form-group ">
                    <label for="lname">Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>
                  
                
                <button type="submit" class="btn btn-primary form-control">Create User</button>
              </form>
      </div>
      
    </div>
  </div>
</div>