        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
           <div class="mb-3" style="">
            <h1 class="h3 mb-0 text-gray-800">Roles</h1>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#createRoleModal">create role</button>
          </div>
         
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
           
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Role</th>
                      <th>Permissions</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                      <?php  foreach ($roles as $item ) { ?>
                        <tr>
                          <td> <?= $item['name'] ?> </td>
                          <td> 
                            <?= $item['permissions'] ?>
                          </td>
                          <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                              <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editRoleModal<?= $item['id'] ?>">edit</button>
                              <a href="/roles/delete/<?= $item['log_id'] ?>" class="btn btn-danger">delete</a>
                            </div>
                          </td>
                          
                          
                        </tr>
                      <?php } ?>
                   
                   
                    
                   
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

<!-- Create role modal -->


<!-- Modal -->
<div class="modal fade" id="createRoleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Create role</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="">
          <div class="form-group">
            <label for="exampleInputEmail1">Role name</label>
            <input type="text" class="form-control" id="permissionName" aria-describedby="emailHelp" placeholder="Enter role name" name="name">
          </div>

          <?php foreach($permissions as $permission): ?>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="<?= $permission['name'] ?>" name="permissions[]"  >
              <label class="form-check-label" for="defaultCheck1">
                <?= $permission['name'] ?>
              </label>
            </div>
            <?php endforeach; ?>
          
          <button type="submit" class="btn btn-dark btn-sm ">Create role</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<!-- Edit permission  -->

 <?php  foreach ($roles as $item ) { ?>
<!-- Modal -->
<div class="modal fade" id="editRoleModal<?= $item['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" >Edit role</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/roles/edit/<?= $item['log_id'] ?>">
          <div class="form-group">
            <label for="exampleInputEmail1">Permission name</label>
            <input type="text" class="form-control" id="permissionName" aria-describedby="emailHelp" value="<?= $item['name'] ?>" placeholder="Enter permission name" name="role_name">
          </div>

          <?php foreach($permissions as $permission): ?>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="<?= $permission['name'] ?>" name="permissions[]" <?php if(in_array($permission['name'], json_decode($item['permissions']))){ echo 'checked'; } ?> >
              <label class="form-check-label" for="defaultCheck1">
                <?= $permission['name'] ?>
              </label>
            </div>
            <?php endforeach; ?>
          
          <button type="submit" class="btn btn-dark btn-sm ">Update role</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<?php } ?>