        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
           <div class="mb-3" style="">
            <h1 class="h3 mb-0 text-gray-800">Permissions</h1>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#createRoleModal">create permission</button>
          </div>
         
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
           
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Role</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                      <?php  foreach ($permissions as $item ) { ?>
                        <tr>
                          <td> <?= $item['name'] ?> </td>
                          <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                              <a href="/roles/permissions/delete/<?= $item['log_id'] ?>" class="btn btn-danger">delete</a>
                            </div>
                          </td>
                          
                          
                        </tr>
                      <?php } ?>
                   
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

<!-- Create role modal -->


<!-- Modal -->
<div class="modal fade" id="createRoleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Create permission</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/roles/permissions/add">
          <div class="form-group">
            <label for="exampleInputEmail1">Permission name</label>
            <input type="text" class="form-control" id="permissionName" aria-describedby="emailHelp" placeholder="Enter permission name" name="name">
          </div>
          
          <button type="submit" class="btn btn-dark btn-sm ">Create permission</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<!-- Edit permission  -->

 <?php  foreach ($permissions as $item ) { ?>
<!-- Modal -->
<div class="modal fade" id="editPermissionModal<?= $item['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" >Edit permission</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/roles/permission/<?= $item['log_id'] ?>/edit">
          <div class="form-group">
            <label for="exampleInputEmail1">Permission name</label>
            <input type="text" class="form-control" id="permissionName" aria-describedby="emailHelp" value="<?= $item['permission'] ?>" placeholder="Enter permission name" name="permission_name">
          </div>
          
          <button type="submit" class="btn btn-dark btn-sm ">Update permission</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<?php } ?>