        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
           <div class="mb-3" style="">
            <h1 class="h3 mb-0 text-gray-800">Categories</h1>
            <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#createCategoryModal">create category</button>
          </div>
         
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
           
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>Category</th>
                      <th>Description</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                      <?php  $counter = 0;  foreach ($categories as $item ) { $counter = $counter+1; ?>
                        <tr>
                          <td> <?= $counter ?> </td>
                          <td> 
                            <?= $item['name'] ?>
                          </td>
                          <td> 
                            <?= $item['description'] ?>
                          </td>
                          <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                              <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#editCategoryModal<?= $item['id'] ?>">edit</button>
                              <a href="/categories/delete/<?= $item['log_id'] ?>" class="btn btn-danger">delete</a>
                            </div>
                          </td>
                          
                          
                        </tr>
                      <?php } ?>
                   
                   
                    
                   
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

<!-- Create role modal -->


<!-- Modal -->
<div class="modal fade" id="createCategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" id="exampleModalLabel">Create category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/categories">
          <div class="form-group">
            <label for="exampleInputEmail1">Category name</label>
            <input type="text" class="form-control" aria-describedby="emailHelp" placeholder="Enter category name" name="name">
          </div>

         <div class="form-group">
          <label for="exampleFormControlTextarea1">Description</label>
          <textarea class="form-control" name="description" rows="3"></textarea>
        </div>
          
          
          <button type="submit" class="btn btn-dark btn-sm ">Create category</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<!-- Edit permission  -->

 <?php  foreach ($categories as $item ) { ?>
<!-- Modal -->
<div class="modal fade" id="editCategoryModal<?= $item['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-dark" >Edit category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/categories/edit/<?= $item['log_id'] ?>">
          <div class="form-group">
            <label for="exampleInputEmail1">Category</label>
            <input type="text" class="form-control" aria-describedby="emailHelp" value="<?= $item['name'] ?>" placeholder="Enter category name" name="name">
          </div>

         <div class="form-group">
          <label for="exampleFormControlTextarea1">Description</label>
          <textarea class="form-control" name="description" rows="3"> <?= $item['description'] ?></textarea>
        </div>
          
          <button type="submit" class="btn btn-dark btn-sm ">Update categoey</button>
        </form>
      </div>
     
    </div>
  </div>
</div>

<?php } ?>