<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/x-icon" href="/img/favicon.png?v=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>FINETOUCH <?php echo $this->tag->getTitle(); ?></title>
        <link href="/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        
      <!-- Custom styles for this template-->
      <link href="/template/css/sb-admin-2.min.css" rel="stylesheet">
      <!-- Custom styles for this page -->
      <link href="/template/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
      <style type="text/css">
        .errorMessage{
          background-color: rgb(224, 45, 27);
          padding: 5px;
          border-radius: 4px;
          margin-top:10px;
          margin-bottom: 10px;
          font-size: 13px;
          color: #fff;
        }
        .successMessage{
          background-color: rgb(28, 200, 138);
          color: #fff;
          padding: 5px;
          border-radius: 4px;
          margin-top:10px;
          margin-bottom: 10px;
          font-size: 13px;
        }
        .noticeMessage{
          background-color: rgb(54, 185, 204);
          color: #fff;
          padding: 5px;
          border-radius: 4px;
          margin-top:10px;
          margin-bottom: 10px;
          font-size: 13px;
        }
        textarea.form-control{
          font-size: 13px!important;
        }

        div{
          font-size: 13px!important;
        }
        input, select{
          font-size: 13px!important;
        }
        table{
          font-size: 13px!important;
        }
        a, button{
          font-size: 10px!important;
        }
        table a, table button{
          font-size: 10px!important;
        }
        label{
          font-size: 13px!important;
        }
        
      </style>
    </head>
    <body>
        <div class="">
            <?php echo $this->getContent(); ?>
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fas fa-angle-up"></i>
            </a>
            <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                  </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                  <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                  <a class="btn btn-primary" href="/auth/logout">Logout</a>
                </div>
              </div>
            </div>
          </div>
        </div>


        <!-- Bootstrap core JavaScript-->
      <script src="/template/vendor/jquery/jquery.min.js"></script>
      <script src="/template/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

      <!-- Core plugin JavaScript-->
      <script src="/template/vendor/jquery-easing/jquery.easing.min.js"></script>

      <!-- Custom scripts for all pages-->
      <script src="/template/js/sb-admin-2.min.js"></script>

      <!-- Page level plugins -->
     
      <script src="/template/vendor/datatables/jquery.dataTables.min.js"></script>
      <script src="/template/vendor/datatables/dataTables.bootstrap4.min.js"></script>

      <!-- Page level custom scripts -->
      <script src="/template/js/demo/datatables-demo.js?v=1"></script>

      
      

    </body>
</html>
