        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-2 text-gray-800">Edit User</h1>
          

          <!-- DataTales Example -->
          <div class="row">
            <div class=" col-md-6 ">
              <div class="card shadow mb-4">
            
            <div class="card-body">
              <form actions="/profile/edit/<?= $user['log_id'] ?>" method="POST">
                  
                   <div class="form-group ">
                    <label for="fname">Full Name</label>
                    <input type="text" class="form-control" placeholder="First Name" name="full_name" value="<?= $user['full_name'] ?>" required>
                  </div>
                  <div class="form-group ">
                    <label for="lname">Phone</label>
                    <input type="text" class="form-control" placeholder="Phone" name="msisdn" value="<?= $user['msisdn'] ?>" required>
                  </div>

                  <hr>

                  <div class="form-group ">
                    <label for="lname">Password</label>
                    <input type="text" class="form-control" placeholder="Password" name="password" >
                  </div>
                  <div class="form-group ">
                    <label for="lname">Confirm Password</label>
                    <input type="text" class="form-control" placeholder="Password" name="password2" >
                  </div>
                
                <button type="submit" class="btn btn-primary form-control">Save Settings</button>
              </form>
            </div>
          </div>
            </div>
          </div>
          

        </div>