        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
           <div class="mb-3" style="">
            <h1 class="h3 mb-1 text-gray-800"><?= $profile['first_name'] . " " . $profile['middle_name'] . " " . $profile['last_name'] ?></h1>
            <p class="text-primary mb-0"> <small class="text-muted">Created: </small> <?= $profile['creation_date'] ?>   <small class="text-muted">Balance: </small> <?= number_format(($profile['credit'] - $profile['debit']), 2) ?> </p>
            <button type="button" class="btn btn-dark btn-sm mb-2" data-toggle="modal" data-target="#exampleModal">
              Debit Participant Wallet
            </button>

          </div>
         
          
          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header">
              Customer Transactions
            </div>
           
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Trans#</th>
                      <th>Amount <small>KES</small> </th>
                      <th>Date</th>
                      <th>Type</th>
                      <th>Desc</th>
                      <th>Ref</th>
                    </tr>
                  </thead>
                 
                  <tbody>
                      <?php  foreach ($transactions as $item ) { ?>
                        <tr>
                          <td> <?= $item['transaction_id'] ?> </td>
                          <td> <?= number_format($item['transaction_amount'], 2) ?> </td>
                          <td> <?= $item['creation_date'] ?> </td>
                          <td> <?= $item['type'] ?> </td>
                          <td> <?= $item['subtype'] ?> </td>
                          <td> <?= $item['transaction_reference'] ?> </td>
                          
                          
                        </tr>
                      <?php } ?>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-primary" id="exampleModalLabel">Debit Participant Wallet</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="/profile/debit/<?= $profile['log_id'] ?>">
          <div class="form-group">
            <label for="exampleInputEmail1">Amount</label>
            <input type="number" class="form-control" placeholder="Enter amount to debit" name="amount">
          </div>

          <div class="form-group">
            <label for="exampleInputEmail1">Remarks</label>
            <input type="text" class="form-control" placeholder="Enter Debit Remarks" name="remarks" max="150">
          </div>
          <button type="submit" class="btn btn-primary btn-sm form-control">Submit</button>
        </form>

      </div>
      
    </div>
  </div>
</div>