


  <!-- Page Wrapper -->
  <div id="wrapper">

    <?php

	include __DIR__ . "/../components/sidebar.phtml";

	?>

    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <?php

		include __DIR__ . "/../components/topbar.phtml";

		?>
        <div class="container-fluid">
          <?php echo $this->flashSession->output(); ?>
        </div>
        <?php echo $this->getContent(); ?>
       

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2020</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>

  </div>